name: Tests

on: [push]

jobs:
  tests:
    name: Ubuntu Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - run: pip install meson ninja
      - run: meson setup build
      - run: meson test -C build
